config/routes.rb
Rails.application.routes.draw do
  resources :food_items do
    resources :orders
    resources :reviews
  end
  get 'menu' => 'home#menu'
  get 'contact_us' => 'home#contact_us'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
  validates :name, :price, presence: true
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy
  is_impressionable

  def self.search(search)
    where("name ILIKE ?", "#{search}")
  end

  def image_url_or_default
    image_url.presence || "http://loremflickr.com/480/480/#{name.strip}"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :food_item
  validates :name, :phone_number, :address, presence: true
  validates :quantity, presence: true, numericality: true

  def total_price_calc
    self.total_price = self.coupon_code == 'CODERSCHOOL' ? (self.food_item.price * self.quantity) / 2 :
                                                           (self.food_item.price * self.quantity)
    self.total_price += 20000
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :food_item
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :food_items, dependent: :destroy

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]
  impressionist :actions=>[:show]
  add_flash_types :success, :warning, :error, :info

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
    @food_item.hit_count = @food_item.impressionist_count
    @food_item.save

    @reviews = @food_item.reviews.to_a
    @avg_rating = @reviews.blank? ? 0 : @food_item.reviews.average(:rating).floor
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to food_items_url, success: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to food_items_url, info: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_path, error: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section_id, :image_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def menu
    @sections = Section.all
    if params[:section_id].present?
      @current_section = Section.find(params[:section_id])
      @items = @current_section.food_items
    else
      @items = FoodItem.all
    end

    if params[:search]
      @items = FoodItem.search(params[:search])
    end

    if params[:sort_column]
      @items = @items.order("#{params[:sort_column]} #{params[:sort_type]}")
    end
  end

  def contact_us
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  add_flash_types :success, :warning, :danger, :info

  def index
    @item = FoodItem.find(params[:food_item_id])
    @orders = @item.orders.all
  end

  def show
  end

  def new
    @item = FoodItem.find(params[:food_item_id])
    @order = Order.new(food_item: @item) #@item.orders.build
  end

  def create
    @item = FoodItem.find(params[:food_item_id])
    @order = @item.orders.build order_params
    @order.total_price_calc

    if @order.save
      redirect_to food_item_order_path(id: @order.id)
      flash[:success] = "Thank you for your order."
    else
      render 'new'
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to food_item_orders_path, info: "Order was successfully destroyed." }
    end
  end

  def set_order
    @item = FoodItem.find(params[:food_item_id])
    @order = @item.orders.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:name, :phone_number, :address, :quantity, :coupon_code)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @food_item = FoodItem.find(params[:food_item_id])
    @review = @food_item.reviews.create review_params
    redirect_to food_item_path(id: @food_item.id)
  end

  def destroy
    @food_item = FoodItem.find(params[:food_item_id])
    @review = @food_item.reviews.find(params[:id])
    @review.destroy
    redirect_to food_item_path(id: @food_item.id)
  end

  private
    def review_params
      params.require(:review).permit(:reviewer, :comment, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: 'alert-success', info: 'alert-info', error: 'alert-danger', notice: 'alert-warning'}[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.map do |msg_type, message|
      content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade show") do
        content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'}) + message
      end
    end.join.html_safe
  end
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/food_items/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<div style="color: #FFFFFF">
  <%= form_for(food_item) do |f| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-danger"><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control'%>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :section_id %>
    <%= f.select :section_id, Section.all.map {|s| [s.name, s.id]}, {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url, class: 'form-control' %>
  </div><br>

  <%= f.submit 'Update', class: 'btn btn-warning' %>
<% end %>
</div>
</body>
</html>

app/views/food_items/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<h1><span style="color: #FFFFFF">Editing Food Item</span></h1>

<%= render 'form', food_item: @food_item %>
<%= link_to 'Show', @food_item, class: 'btn btn-info'%>
<%= link_to 'Back', food_items_path, class: 'btn btn-secondary' %>
</body>
</html>

app/views/food_items/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<h1 style="color: #FFFFFF;">Food Items</h1>
<table class="table table-inverse table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><%= food_item.image_url %></td>
        <td><%= link_to 'Show', food_item, class: 'btn btn-info' %> </td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Food Item', new_food_item_path, class: 'btn btn-primary' %>
</body>
</html>

app/views/food_items/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<h1><span style="color: #FFFFFF">New Food Item</span></h1>

<%= render 'form', food_item: @food_item %>
<%= link_to 'Back', food_items_path, class: 'btn btn-secondary' %>
</body>
</html>

app/views/food_items/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-8">
    <div class="card">
      <img class="card-img-top" src=<%= @food_item.image_url_or_default %> alt=<%= @food_item.name %> height="400">
      <div class="card-block">
        <h4 class="card-title"><%= @food_item.name %></h4>
        <i class="fa fa-eye" style="display:inline-block;width: 20px;"></i><span style="display:inline-block;min-width: 30px;"><%= @food_item.hit_count %></span>
        <i class="fa fa-comments" style="display:inline-block;width: 20px;"></i><span style="display:inline-block;min-width: 30px;"><%= @food_item.reviews.count %></span>
        <div class="star-rating" data-score= <%= @avg_rating %> ></div>
        <p><%= @food_item.description %></p>
        <%= link_to "#{number_to_currency(@food_item.price, precision: 0, unit: "VND", delimiter: ",", format: "%n %u")}", new_food_item_order_path(food_item_id: @food_item.id), class: 'btn btn-warning' %>
      </div>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="card">
      <%= render 'reviews/form' %>
    </div><br>
    <div class="card">
      <h3 class="card-header" id="review">Review</h3>
      <%= render @food_item.reviews %>
    </div>
  </div>
</div>
</body>
</html>

app/views/home/contact_us.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<div class="row">
  <div class="col-sm-6">
    <div class="card card-block">
      <h3>Our story</h3>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </div><br>
    <div class="card card-block">
      <address>
        <i class="fa fa-cutlery" style="display:inline-block;width: 20px;"></i><span style="display:inline-block;min-width: 30px;">Il Gustoso</span><br>
        <i class="fa fa-map-marker" style="display:inline-block;width: 20px;"></i><span style="display:inline-block;min-width: 30px;">72 Le Thanh Ton Street, District 1</span><br>
        <i class="fa fa-phone" style="display:inline-block;width: 20px;"></i><span style="display:inline-block;min-width: 30px;">(84) 123-456-789</span>
      </address>
    </div>
  </div>
  <div class="col-sm-6">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.431380710506!2d106.69937171450339!3d10.778235262108234!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f47df59b94f%3A0x6bbcaeb33e29c9f2!2sVincom+Center+B+Shopping+Mall!5e0!3m2!1sen!2s!4v1487046491658" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
</div>

</body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<div class="jumbotron">
  <div class="row">
  
    <div class="col-sm-6">
        <h1>Welcome to</h1>
        <p style="font-size: 96px">Il Gustoso</p>
        <span style="padding-top: 20px;"><%= link_to "Discover", menu_path, class: 'btn btn-lg btn-outline-secondary' %></span>
    </div>

    <div class="col-sm-6">
      <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active">
            <img class="d-block img-fluid" src="http://www.viumanent.cl/wp/wp-content/uploads/2009/09/CF106576.jpg" alt="First slide" height="480" width="480">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="http://dyhqy1pgs6687.cloudfront.net/AIDAIA77AWCA6KEC5QGES/cms/cache/480x480/a0/375-a017c47ec4afd90279a37755109b27c6.JPG" alt="Second slide" height="480" width="480">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="https://www.foodanddrinkguides.co.uk/sites/default/files/styles/large/public/bramblings_restaurant_-_abbey_hotel_-_interior.jpg?itok=hfmrPnt5" alt="Third slide" height="480" width="480">
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
</body>
</html>

app/views/home/menu.html.erb
<div class="container" id="filter">
  <div class="row">
    <div class="btn-group">
      <% @sections.each do |section| %>
        <%= link_to section.name, menu_path(section_id: section.id), class: "btn #{params[:section_id] == section.id.to_s ? 'btn-warning' : 'btn-secondary'}" %>
      <% end %>
    </div>
    <div id="search">
      <%= form_tag nil, method: 'get' do %>
        <%= hidden_field_tag :section_id, params[:section_id] %>
        <div class="form-inline" style="padding-left: 25px;">
          <%= select_tag :sort_column, options_for_select([['Name','name'], ['Price','price'],['Views','hit_count']]), class: 'form-control' %>
          <%= select_tag :sort_type, options_for_select([['Ascending','asc'], ['Descending','desc']]), class: 'form-control' %>
          <%= submit_tag 'Sort', class: 'btn btn-warning' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <% if @items %>
      <% @items.each do |item| %>
        <div class="col-sm-4">
          <div class="card" id="c-card">
            <div class="views text-white">
              <i class="fa fa-eye" style="display:inline-block;width: 30px;"></i><span style="display:inline-block;min-width: 30px;"><%= item.hit_count %></span>
              <i class="fa fa-comments" style="display:inline-block;width: 30px;"></i><span style="display:inline-block;min-width: 30px;"><%= item.reviews.count %></span>
            </div>
            <img class="card-img" src= <%= item.image_url_or_default %> alt= <%= item.name %> height="320">
            <div class="card-block">
              <h4 class="card-title"><%= link_to "#{item.name}", food_item_path(item), class: 'badge badge-info' %></h4>
              <%= link_to "#{number_to_currency(item.price, precision: 0, unit: "VND", delimiter: ",", format: "%n %u")}", new_food_item_order_path(food_item_id: item.id), class: 'btn btn-warning' %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<nav class="navbar navbar-toggleable-md navbar-inverse bg-faded" style="background-color: #A7D2CB; margin-bottom: 20px">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="<%= root_path %>">Il Gustoso</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href=<%= menu_path %> >Menu<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%= contact_us_path %> >Contact Us</a>
      </li>
    </ul>
      <form class="form-inline my-2 my-lg-0">
        <%= form_tag menu_path, method: 'get' do %>
        <%= text_field_tag :search, params[:search], class: 'form-control mr-sm-2', placeholder: 'Search' %>
        <%= submit_tag 'Search', class: 'btn btn-warning my-2 my-sm-0'%>
        <% end %>
      </form>
  </div>
</nav>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Il Gustoso</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<div style="color: #FFFFFF">
<%= form_for [item, order] do |f| %>
  <% if order.errors.present? %>
    <div class="alert alert-danger"><%= order.errors.full_messages.to_sentence %></div>
  <% end %>
  <div class="form-group">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: 'form-control' %>
    </div>
    
    <div class="field">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :quantity %>
      <%= f.number_field :quantity, class: 'form-control' %>
    </div>

    <div class="field" >
      <%= f.label :coupon_code %>
      <%= f.text_field :coupon_code, class: 'form-control'%>
    </div>
  </div>
  <%= f.submit 'Checkout', class: 'btn btn-success' %>
<% end %>  
</div>
</body>
</html>

app/views/orders/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<h1><span style="color: #FFFFFF">Orders of <%= @item.name %></span></h1>

<table class="table table-inverse table-striped table-bordered">
  <thead>
    <tr>
      <th>Customer</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.phone_number %></td>
        <td><%= order.address %></td>
        <td><%= order.quantity %></td>
        <td><%= link_to 'Show', food_item_order_path(id: order.id), class: 'btn btn-info' %></td>
        <td><%= link_to 'Destroy', food_item_order_path(id: order.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</body>
</html>

app/views/orders/new.html.erb
<h1><span style="color: #FFFFFF">Order for <%= @item.name %></span></h1>

<%= render 'form', item: @item, order: @order %>

app/views/orders/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<h1><span style="color: #FFFFFF">Your order detail information</span></h1>
<div class="jumbotron">
  <div class="row">
    <div class="col-sm-2">
      <p>Customer:</p>
      <p>Address:</p>
      <p>Phone:</p>
      <p>Time order:</p>
    </div>
    <div class="col-sm-4">
      <p><%= @order.name %></p>
      <p><%= @order.address %></p>
      <p><%= @order.phone_number %></p>
      <p><%= @order.created_at.strftime("%A, %d %b %Y %l:%M %p") %></p>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th>Item</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Cost</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @order.food_item.name %></td>
          <td><%= number_to_currency(@order.food_item.price, precision: 0, unit: "VND", delimiter: ",", format: "%n %u") %></td>
          <td><%= @order.quantity %></td>
          <td><%= number_to_currency(@order.food_item.price * @order.quantity, precision: 0, unit: "VND", delimiter: ",", format: "%n %u") %></td>
        </tr>
        <tr>
          <td>Delivery cost</td>
          <td></td>
          <td></td>
          <td><%= number_to_currency(20000.0, precision: 0, unit: "VND", delimiter: ",", format: "%n %u") %></td>
        </tr>
        <% if @order.coupon_code.presence %>
          <tr>
            <td>Discount</td>
            <td></td>
            <td></td>
            <td><%= number_to_currency((@order.food_item.price * @order.quantity) / 2, precision: 0, unit: "VND", delimiter: ",", format: "%n %u")%></td>
          </tr>
        <% end %>
        <tr>
          <td>Total cost</td>
          <td></td>
          <td></td>
          <td><%= number_to_currency(@order.total_price, precision: 0, unit: "VND", delimiter: ",", format: "%n %u") %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
</body>
</html>

app/views/reviews/_form.html.erb
<h3 class="card-header" id="n-review">New review</h3>
<div class="card-block">
  <%= form_for([@food_item, @food_item.reviews.build]) do |f| %>
    <div id='star-rating'></div>
    <br><div class="field">
      <%= f.text_field :reviewer, class: 'form-control', placeholder: 'Name' %> 
    </div><br>
    <div class="field">
      <%= f.text_field :comment, class: 'form-control', placeholder: 'Comment' %> 
    </div><br>
    <div class="float-xl-right">
      <%= f.submit 'Submit', class: 'btn btn-warning' %>
    </div>
  <% end %>
</div>

<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
  
  $('#star-rating').raty({
    path: '/assets',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="card-block">
  <h4 class="card-title"><strong><%= review.reviewer %></strong></h4>
  <div class="card-text"><%= review.comment %></div>
  <% if review.rating %>
    <div class="star-rating" data-score= <%= review.rating %> ></div>
  <% end %>
</div>

<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
    
  $('#star-rating').raty({
    path: '/assets',
    scoreName: 'review[rating]'
  });
</script>